### ISSUE TITLE
Docker Image

### ISSUE THREAD

**Issue by ajhorvath20** [comixed/comixed#691]
Hi, apologise if I read it wrong but I think its not available publicly? Because I just spin the image and docker couldn't find the manifest. 
```
  comixed:
    image: comixed/comixed:release
    hostname: ${DOCKERHOSTNAME}
    ports:
      - 7171:7171
    container_name: comixed
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    restart: unless-stopped
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - ${DOCKERCONFDIR}/comixed:/root/.comixed
    - ${DOCKERSTORAGEDIR}:/storage
```
Thanks
